### PR TITLE
Fix typos in readme.md

### PR DESCRIPTION
**Pull request by mcepl**

### CODE REVIEW

**Comment by thomasballinger** [comment]
@mcepl did you try out this library? Does it still work / is it still useful?

**Comment by mcepl** [comment]
@thomasballinger , no, just saw the typo ;)

**Comment by thomasballinger** [comment]
Ah, thanks for fixing then! Unfortunately I think I'll take this down, but at least a file on my hard drive will be slightly less wrong :)

**Comment by thomasballinger** [comment]
Actually you know what this is fine, I'm just going to update the readme to say it's outdated.

**Pull request merged**
